#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math, RoutingTable

class Router:

    relations = {}
    sockets = {}
    ports = {}
    table = RoutingTable.RoutingTable()

    def __init__(self, asn, connections):
        print("Router at AS %s starting up" % asn)
        self.asn = asn
        for relationship in connections:
            port, neighbor, relation = relationship.split("-")

            self.sockets[neighbor] = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            self.sockets[neighbor].bind(('localhost', 0))
            print("Bound to port:", self.sockets[neighbor].getsockname()[1])
            self.ports[neighbor] = int(port)
            self.relations[neighbor] = relation
            handshakeMsg = json.dumps({ "type": "handshake", "src": self.our_addr(neighbor), "dst": neighbor, "msg": {}  })
            print(handshakeMsg)
            self.send(neighbor, handshakeMsg)

    def our_addr(self, dst):
        quads = list(int(qdn) for qdn in dst.split('.'))
        quads[3] = 1
        return "%d.%d.%d.%d" % (quads[0], quads[1], quads[2], quads[3])

    def send(self, network, message):
        self.sockets[network].sendto(message.encode('utf-8'), ('localhost', self.ports[network]))
        print("sent data to %s" % (network))

    def run(self):
        while True:
            socks = select.select(self.sockets.values(), [], [], 0.1)[0]
            for conn in socks:
                k, addr = conn.recvfrom(65535)
                srcif = None
                for sock in self.sockets:
                    if self.sockets[sock] == conn:
                        print(sock)
                        srcif = sock
                        break
                msg = k.decode('utf-8')

                print("Received message %s from %s" % (msg, srcif))
                self.handle_message(msg, srcif)
        return
    
    def handle_message(self, msg, srcif):
        msgDict = json.loads(msg)
        match msgDict['type']:
            case 'handshake':
                self.__handle_handshake(msgDict)
            case 'update':
                self.__handle_update(srcif, msgDict)
            case 'withdraw':
                self.__handle_withdraw(msgDict)
            case 'data':
                self.__handle_data(msgDict)
            case _:
                print("unknown message type")

    
    def __handle_update(self, srcif, updateMsg):
        self.table.add_message(updateMsg)

        updateMsg['msg']['ASPath'].insert(0, self.asn)
        updateMsg['msg']['selfOrigin'] = False

        for neighbor in self.sockets:
            if neighbor == srcif:
                continue  
            
            if self.relations[srcif] != 'cust' and self.relations[neighbor] != 'cust':
                continue

            fwd = {
                "type": "update",
                "src": self.our_addr(neighbor),
                "dst": neighbor,
                "msg": updateMsg['msg']
            }
            self.send(neighbor, json.dumps(fwd))

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='route packets')
    parser.add_argument('asn', type=int, help="AS number of this router")
    parser.add_argument('connections', metavar='connections', type=str, nargs='+', help="connections")
    args = parser.parse_args()
    router = Router(args.asn, args.connections)
    router.run()